[general]
# Lower bars make it look cleaner in the bar
bars = 8
framerate = 60
autosens = 1
overshoot = 0
sens = 60


[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 7
channels = mono
integral = 50

